//
// HkTdmErrors.h
//
//  Created by Faber on 13 Jul 2022
//  Copyright © 2018 Faber. All rights reserved.
//

#ifndef HKTDM_ERRORS_H
#define HKTDM_ERRORS_H

	// List of errors
	typedef enum HKTDM_Error_enum {
		HKTDM_ERR_NO_ERROR = 0,
		HKTDM_ERR_COMMUNICATION,
		HKTDM_ERR_COMMAND_NOT_FOUND,
		HKTDM_ERR_PARAM_ERROR,

		HKTDM_ERR_PACKET_OK,
		HKTDM_ERR_PACKET_ERROR,

		// HKTDM_ERR_ADS1115_INIT,
		// HKTDM_ERR_ADS1115_WRITECONFREG,
		// HKTDM_ERR_ADS1115_BEGINCONV,
		// HKTDM_ERR_ADS1115_READCONV,

		// HKTDM_ERR_CHANNEL_NUM,
		// HKTDM_ERR_THR_VALUE,
		// HKTDM_ERR_CALMUX,

		// HKTDM_ERR_AD5665R_INIT,
		// HKTDM_ERR_AD5665R_SWRST,
		// HKTDM_ERR_AD5665R_DIS_LDAC,
		// HKTDM_ERR_AD5665R_SETREFON,
		// HKTDM_ERR_AD5665R_CHA,
		// HKTDM_ERR_AD5665R_CHB,
		// HKTDM_ERR_AD5665R_CHC,
		// HKTDM_ERR_AD5665R_CHD,
		
		// HKTDM_ERR_SHT21_MEASURE,
		// HKTDM_ERR_SHT21_READ,

		// HKTDM_ERR_SI5345_PLLINIT,
		HKTDM_ERR_MENU_DISPLAY,
		// HKTDM_ERR_DS1820_INVALID,
		HKTDM_ERR_BOARD_INIT
	} HKTDM_Error_type;

// returns a string based on error number
const char* getHkTdmErrorString(HKTDM_Error_type _err);

#endif /* HKTDM_ERRORS_H */
